name: Automated Testing using Postman CLI

on: # Tiggers the workflow on push event for muster branch
  push:
    branches: [master]
  workflow_dispatch:  # Allow workflow to be manually trigger in Github Action

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      # checkout repository
      - uses: actions/checkout@v4
      - name: Create report folder
        run: |
          mkdir results

      # Install NodeJS
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # install newman and reporter
      - name: Install newman and reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # run collection
      - name: run collection
        run: |
          newman run ReqResApiTest.postman_collection.json -e reqres.postman_environment.json -r htmlextra --reporter-htmlextra-export results/report.html

      # publish reports
      - name: Publish report
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: results